FROM node:22-alpine AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --configuration=production

FROM nginx:alpine

COPY --from=build /app/dist/bank_meet/browser /usr/share/nginx/html
EXPOSE 80